spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.udp=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.udp.type=hive
spark.sql.catalog.udp.uri=thrift://hive-metastore:9083
spark.sql.catalog.udp.warehouse=s3a://datalake/warehouse
spark.sql.catalog.udp.io-impl=org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.udp.s3.endpoint=http://minio:9000
spark.sql.catalog.udp.s3.path-style-access=true
spark.sql.defaultCatalog=udp
spark.hadoop.fs.s3a.endpoint=http://minio:9000
spark.hadoop.fs.s3a.access.key=admin
spark.hadoop.fs.s3a.secret.key=udp_admin_12345
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
