#!/usr/bin/env python3
"""Render StarRocks RBAC SQL from governance policy YAML.

Reads governance/policies/*.yaml, emits sql/starrocks/02_create_users.sql.template
with ${ROLE_*_PASSWORD} placeholders, and appends those env vars to .env (with
randomly generated values) so render-templates.sh can substitute them.

Idempotent: if a role's credential is already in .env, it is reused.

Row filters in policy YAML are emitted as TODO comments — StarRocks 3.3 supports
row policies but the syntax/feature set varies by release; encode them in Phase 7
when we add the policy enforcement layer.
"""
from __future__ import annotations

import secrets
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml required. pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO = Path(__file__).resolve().parent.parent
POLICY_DIR = REPO / "governance" / "policies"
OUTPUT_TEMPLATE = REPO / "sql" / "starrocks" / "02_create_users.sql.template"
ENV_FILE = REPO / ".env"


def gen_secret() -> str:
    return secrets.token_hex(16)


def env_var_for(role: str) -> str:
    return f"STARROCKS_{role.upper()}_PASSWORD"


def read_env() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k] = v
    return out


def append_env(new_pairs: dict[str, str]) -> None:
    existing = read_env()
    additions = [f"{k}={v}" for k, v in new_pairs.items() if k not in existing]
    if not additions:
        return
    content = ENV_FILE.read_text() if ENV_FILE.exists() else ""
    if content and not content.endswith("\n"):
        content += "\n"
    content += "\n# Generated by scripts/generate-starrocks-users.py\n"
    content += "\n".join(additions) + "\n"
    ENV_FILE.write_text(content)
    try:
        ENV_FILE.chmod(0o600)
    except OSError:
        pass


def render_sql_template(roles: dict[str, dict]) -> str:
    lines: list[str] = [
        "-- AUTO-GENERATED by scripts/generate-starrocks-users.py from governance/policies/*.yaml",
        "-- Do not edit by hand. Re-run the generator after policy changes.",
        "",
    ]
    for role, cfg in roles.items():
        env_var = env_var_for(role)
        lines.append(f"-- Role: {role}")
        lines.append(
            f"CREATE USER IF NOT EXISTS '{role}'@'%' IDENTIFIED BY '${{{env_var}}}';"
        )
        for obj in cfg.get("allow", []) or []:
            # StarRocks 3.x: bare "GRANT SELECT ON <obj>" defaults to TABLE and
            # fails for views with "cannot find table". The demo policy grants
            # on views (app_analytics.demo_customer_summary). Until the policy
            # YAML schema carries an object-type field, default to VIEW because
            # that's what the analytics layer exposes. For raw tables, change
            # the GRANT manually or extend the schema (Phase 7).
            lines.append(f"GRANT SELECT ON VIEW {obj} TO '{role}'@'%';")
        for obj, filt in (cfg.get("row_filters") or {}).items():
            lines.append(f"-- TODO row filter: {role} on {obj} where {filt!r}")
        for obj, masks in (cfg.get("column_masks") or {}).items():
            lines.append(f"-- TODO column mask: {role} on {obj}: {masks!r}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not POLICY_DIR.exists():
        print(f"ERROR: {POLICY_DIR} not found", file=sys.stderr)
        return 1

    merged_roles: dict[str, dict] = {}
    for path in sorted(POLICY_DIR.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text())
        for role, cfg in (doc.get("roles") or {}).items():
            if role in merged_roles:
                print(
                    f"WARN: role '{role}' defined in multiple policies — last wins",
                    file=sys.stderr,
                )
            merged_roles[role] = cfg

    if not merged_roles:
        print("No roles found in policies/. Nothing to do.")
        return 0

    existing = read_env()
    new_env: dict[str, str] = {}
    for role in merged_roles:
        ev = env_var_for(role)
        if ev not in existing:
            new_env[ev] = gen_secret()
    append_env(new_env)

    sql = render_sql_template(merged_roles)
    OUTPUT_TEMPLATE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_TEMPLATE.write_text(sql)
    print(f"Generated {OUTPUT_TEMPLATE.relative_to(REPO)}")
    if new_env:
        print(f"Added {len(new_env)} role credential(s) to .env: {', '.join(new_env)}")
    else:
        print("All role credentials already in .env (reusing)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
